local_backend: true
backend:
  name: git-gateway
media_folder: 'static/media'
public_folder: '/media'
display_url: https://your-site.com
publish_mode: editorial_workflow
i18n:
  structure: multiple_folders
  locales: [ca, es, en]
  default_locale: ca
collections:
  - name: 'menu'
    label: 'Menu'
    i18n:
      structure: single_file
      locales: [ca, es, en]
    files:
      - name: 'main'
        label: 'Main menu'
        file: 'src/lib/data/menu.json'
        i18n: true
        fields:
          - label: Entries
            name: entries
            widget: 'list'
            allow_add: true
            i18n: true
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Link', name: 'slug', widget: 'string' }
              - { label: 'Order', name: 'order', widget: 'number' }
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    i18n: true
    extension: 'json'
    label: 'Pages' # Used in the UI
    folder: 'src/lib/data' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Metadescription', name: 'metadescription', widget: 'string', i18n: true }
      - label: 'Background'
        name: 'background'
        widget: 'object'
        collapsed: true
        i18n: true
        fields:
          - { label: 'Image', name: 'src', widget: 'image', required: false }
          - { label: 'Imagen alt text', name: 'alt', widget: 'string', required: false, i18n: true }
          - { label: 'P5 Code', name: 'code', widget: 'string', required: false }
          - {
              label: 'Enable P5 (check only if P5 code is present)',
              name: 'isP5enabled',
              widget: 'boolean',
              default: false
            }
      - label: 'Contact'
        name: 'contact'
        widget: 'object'
        collapsed: true
        required: false
        i18n: true
        fields:
          - { label: 'Image', name: 'src', widget: 'image', required: false }
          - { label: 'Image alt text', name: 'alt', widget: 'string', required: false, i18n: true }
          - { label: 'Text', name: 'text', widget: 'markdown', i18n: true, required: false }
      - label: 'Projects'
        name: 'projects'
        widget: 'list'
        collapsed: false
        i18n: true
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Subtitle', name: 'subtitle', widget: 'markdown', required: false }
          - {
              label: 'Card size',
              name: 'size',
              widget: 'select',
              options: ['small', 'medium', 'large']
            }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: 'YYYY-MM' }
          - label: 'Images'
            name: 'images'
            widget: 'list'
            allow_multiple: true
            required: true
            collapsed: false
            fields:
              - { label: 'Image', name: 'src', widget: 'image', required: true }
              - { label: 'Image Alt', name: 'alt', widget: 'string', required: false }
      - label: 'Timeline projects'
        name: 'timelineProjects'
        widget: 'list'
        collapsed: false
        i18n: true
        fields:
          - { label: 'Description', name: 'description', widget: 'string', required: true }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM' }
